spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/t1?useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lldj123414